### ISSUE TITLE
Configuration example is outdated

### ISSUE THREAD

**Issue by vitalyisaev2** [noxiouz/docker-registry-driver-elliptics#20]
Hello, I was trying to deploy Docker Registry server with Elliptics backend inside Docker container, but the configuration example that you provide is no longer suitable. This is the one I ended up with - need to change the **elliptics_verbosity** value:

```
elliptics:
    <<: *common
    storage: elliptics
    elliptics_nodes: ["localhost:1025:2"]
    elliptics_wait_timeout: 60
    elliptics_check_timeout: 60
    elliptics_io_thread_num: 2
    elliptics_net_thread_num: 2
    elliptics_nonblocking_io_thread_num: 2
    elliptics_groups: [2]
    elliptics_verbosity: "debug"
    elliptics_logfile: "/var/log/docker-registry-elliptics.log"
```

Tested with the following packages:

```
# dpkg -l | grep elliptics
ii  elliptics                              2.26.3.33                        amd64        Distributed hash table storage
ii  elliptics-client                       2.26.3.33                        amd64        Distributed hash table storage (client library)
# pip freeze | grep docker
docker-registry==0.9.1
docker-registry-core==2.0.3
docker-registry-driver-elliptics==0.1.1
```
